import Sidebar from "@/components/layout/Sidebar";
import Hedear from "@/components/layout/Header";
import PageBreadCrumb from "./components/PageBreadCrumb";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Bridge Works",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-w-[1280px]`}>
        <div className="flex min-h-screen min-w-full">
          <Sidebar />
          <div className="flex flex-col flex-auto">
            <Hedear />
            <div className="flex-auto bg-secondary px-7 py-5 rounded-2xl">
              {/* <PageBreadCrumb /> */}
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
